### PR TITLE
Added command for the nepdoc link

### PR DESCRIPTION
**Pull request by zfbx**
A lot of people prefer this help document and like to have it on hand.

### CODE REVIEW

**Comment by Marenthyu** [comment]
We tried to stay somewhat independant of it, but i guess there's no real harm in embracing it further.

I'd refer the command to respond with a full sentence instead of just the link though.

Otherwise LGTM

**Comment by Marenthyu** [comment]
Any comments @xorhash ?

**Comment by xorhash** [comment]
`!secretdoc` used to exist. I see no harm in having the command.

> I'd [p]refer the command to respond with a full sentence instead of just the link though.

I don't really see much point in that; the only people who'd try to use it either probably already know what it is.

I'd suggest adding a new config variable to read the URL from. I occasionally move the thing around (happened at least twice in 1.5 years); having to restart the bot and push a code update for a minor change like that is pretty brutal.

**Comment by zfbx** [comment]
How is this @Marenthyu ?

**Comment by Marenthyu** [comment]
LGTM

**Pull request merged**
